app_samo01/urls.py
from django.urls import path
from .views import AppViewIdx, AppViewPage01

app_name = 'app_name_01'

urlpatterns = [
    path('ns_idx/',
         AppViewIdx.as_view(template_name='app_samp01/index.html'),
         name='name_idx'),
    path('ns_pg01/',
         AppViewPage01.as_view(template_name='app_samp01/page01.html'),
         name='name_pg01'),
]

crud/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add, name='add'),
    url(r'^delete/$', views.delete, name='delete'),
    url(r'^edit/(?P<editing_id>\d+)/$', views.edit, name='edit'),
]

django_test/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('path01/', include('app_samo01.urls')),
    path('crud/', include('crud.urls')),
]

app_samo01/models.py
from django.db import models


class Question(models.Model):
    # id = AutoField(primary_key=True)  # 自動的に追加されるので定義不要
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Choice(models.Model):
    # id = AutoField(primary_key=True)  # 自動的に追加されるので定義不要
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

crud/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    # bookid : INTEGER型で、主キー
    bookid = models.IntegerField(primary_key=True)
    # 書名 : 文字列100桁
    title = models.CharField(max_length=100)
    # 著者 : 文字列30桁
    author = models.CharField(max_length=30)

app_samo01/views.py
from django.views.generic.base import TemplateView


class AppViewIdx(TemplateView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["app"] = "Index"
        return context


class AppViewPage01(TemplateView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["app"] = "Page01"
        return context

crud/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return render(request, 'crud/index.html', {})


def add(request):
    return render(request, 'crud/edit.html', {})


def edit(request, editing_id):
    return render(request, 'crud/edit.html', {})


def delete(request):
    return HttpResponse('Delete')

templates/app_samp01/index.html
<html>
  <head>
    <title>{{app}}ページだよ♪</title>
  </head>
  <body>
    <p>ここは、＜{{app}}＞です.</p>
  </body>
  <a href="{% url 'app_name_01:name_pg01' %}">Page01へのリンクだよ</a>
</html>

templates/app_samp01/page01.html
<html>
  <head>
    <title>{{app}}だよ♪</title>
  </head>
  <body>
    <p>ここは、＜{{app}}＞です.</p>
  </body>
  <a href="{% url 'app_name_01:name_idx' %}">Indexへのリンクだよ</a>
</html>

templates/base.html
<!DOCTYPE html>
<html>
<head lang="ja">
  <meta charset="UTF-8">
  <title></title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

templates/crud/edit.html
{% extends "base.html" %}

{% block body %}
    edit
{% endblock %}

templates/crud/index.html
{% extends "base.html" %}

{% block body %}
    index
{% endblock %}